name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]

defaults:
  run:
    working-directory: ./cassandra/app

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        #cache: 'npm'
        #cache-dependency-path: ./cassandra/app/package-lock.json
    - name: Install dependencies
      run: npm install
    - name: Run NPM CI
      run: npm ci
    - name: Build app
      run: npm run build --if-present
    - name: Test app
#      run: npm test # currently no tests defined
