version: '3'


networks:
  spaceandtime:
    ipam:
      config:
        - subnet: 172.20.0.0/24 # static ip management required for cassandra web, as this does not work with docker dns

services:
  raven1:
    container_name: raven1
    image: ravendb/ravendb:5.3-ubuntu-latest
    ports:
      - 8080:8080
      - 38888:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=Unsecured
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
    networks:
      spaceandtime:
          ipv4_address: 172.20.0.6
    
  raven2:
    container_name: raven2
    image: ravendb/ravendb:5.3-ubuntu-latest
    ports:
      - 8081:8080
      - 38889:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=Unsecured
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
    networks:
      spaceandtime:
          ipv4_address: 172.20.0.7

  raven3:
    container_name: raven3
    image: ravendb/ravendb:5.3-ubuntu-latest
    ports:
      - 8082:8080
      - 38890:38888
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=Unsecured
      - RAVEN_License_Eula_Accepted=true
      - "RAVEN_ServerUrl=http://0.0.0.0:8080"
    networks:
      spaceandtime:
          ipv4_address: 172.20.0.8