#version: "3.9"  # optional since v1.27.0

networks:
  spaceandtime:

services:
  cass1:
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    container_name: cass1
    hostname: cass1
    mem_limit: 2g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 10
    networks:
      - spaceandtime
    ports:
      - "9042:9042"
    volumes:
      - ./data/cass1:/var/lib/cassandra
      - ./etc/cass1:/etc/cassandra
    environment: &environment
        CASSANDRA_SEEDS: "cass1,cass2"
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128
  
  cass2:
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    container_name: cass2
    hostname: cass2
    mem_limit: 2g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 10
    networks:
      - spaceandtime
    ports:
      - "9043:9042"
    volumes:
      - ./data/cass1:/var/lib/cassandra
      - ./etc/cass1:/etc/cassandra
    environment: *environment
    depends_on:
      cass1:
        condition: service_started
  
  cass3:
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    container_name: cass3
    hostname: cass3
    mem_limit: 2g
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 10
    networks:
      - spaceandtime
    ports:
      - "9044:9042"
    volumes:
      - ./data/cass1:/var/lib/cassandra
      - ./etc/cass1:/etc/cassandra
    environment: *environment
    depends_on:
      cass2:
        condition: service_started

  cassweb:
    image: ruby:3.1.2 #latest stable version as of 31.05.2022
    container_name: cassweb
    hostname: cassweb
    command: bash -c "gem install cassandra-web && cassandra-web --hosts 'cass1' --port '9042' --username 'cassandra' --password 'cassandra'"
    networks:
      - spaceandtime
    ports:
      - "3000:3000"
    depends_on:
      cass1:
        condition: service_started
      cass2:
        condition: service_started
      cass3:
        condition: service_started