#version: "3.9"  # optional since v1.27.0

networks:
  spaceandtime:
    driver: bridge


services:
  cass1:
    container_name: cass1
    hostname: cass1
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    networks:
      - spaceandtime
    ports:
      - 9042:9042
      - 7000:7000
    volumes:
    - ./cqlsh:/root/.cassandra
    - ./startup:/tmp/startup
    - ./data/cass2:/var/lib/cassandra
    # - ./etc/cass2:/etc/cassandra
    environment:
      - CASSANDRA_SEEDS=cass1,cass2,cass3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M

  
  cass2:
    container_name: cass2
    hostname: cass2
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    networks:
      - spaceandtime
    ports:
      - 9043:9042
      - 7001:7000

    volumes:
    - ./cqlsh:/root/.cassandra
    - ./startup:/tmp/startup
    - ./data/cass1:/var/lib/cassandra
    environment:
      - CASSANDRA_SEEDS=cass1,cass2,cass3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_NUM_TOKENS=128
      - CASSANDRA_PASSWORD=cassandra
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    depends_on:
      cass1:
        condition: service_started # service_healthy --> sometimes not working, alternativly restart always policy below
    #command: bash -c "chmod 755 tmp/startup/setup/setup_db.sh && ./tmp/startup/setup/setup_db.sh"
  
  cass3:
    container_name: cass3
    hostname: cass3
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    networks:
      - spaceandtime
    ports:
      - 9044:9042
      - 7002:7000    
    volumes:
    - ./cqlsh:/root/.cassandra
    - ./startup:/tmp/startup
    - ./data/cass3:/var/lib/cassandra
    # - ./etc/cass3:/etc/cassandra
    environment:
      - CASSANDRA_SEEDS=cass1,cass2,cass3
      - CASSANDRA_CLUSTER_NAME=cassandra-cluster
      - CASSANDRA_PASSWORD=cassandra
      - CASSANDRA_NUM_TOKENS=128
      - MAX_HEAP_SIZE=2G
      - HEAP_NEWSIZE=200M
    depends_on:
      cass2:
        condition: service_started # service_healthy --> sometimes not working, alternativly restart always policy below

  startup_client:
    container_name: client
    hostname: client
    image: cassandra:4.0.4 #latest lts version as of 31.05.2022
    networks:
      - spaceandtime    
    volumes:
    - ./cqlsh:/root/.cassandra
    - ./startup:/tmp/startup
    - ./data/cass3:/var/lib/cassandra
    # - ./etc/cass3:/etc/cassandra
    depends_on:
      cass1:
        condition: service_started # service_healthy --> sometimes not working, alternativly restart always policy below
      cass2:
        condition: service_started # service_healthy --> sometimes not working, alternativly restart always policy below
      cass3:
        condition: service_started # service_healthy --> sometimes not working, alternativly restart always policy below
    
    command: bash -c "cqlsh cass1 -f ./tmp/startup/setup/setup_db.cql"
